config/routes.rb
Rails.application.routes.draw do

  devise_for :members, controllers: {
    registrations: "public/registrations",
    sessions:      "public/sessions",
    passwords:     "public/passwords"
  }
  
  devise_scope :member do
    post "members/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get '/about'          => 'homes#about', as: 'about'

    resources :members, only: [:index, :show] do
      collection do
        get   'favorite'
        get   'deal'
        get   'quit_form'
        post  'confirm'
        patch 'quit'
      end
      resource :relationships, only: [:create, :destroy] do
        collection do
          get 'subscribings'
          get 'subscribers'
        end
      end
      resources :reports,  only: [:new, :create, :show] do
        collection do
          post 'confirm'
        end
      end
    end
    get   'members/information/edit' => 'members#edit'
    patch 'members/information'      => 'members#update'

    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource  :favorites,     only: [:create, :destroy]
      collection do
        get 'map'
      end
    end

    resources :notifications, only: [:destroy] do
      collection do
        delete 'destroy_all'
        patch  'notice'
      end
    end

    resources :searches,    only: [:index]
    resources :tags,        only: [:show]
    resources :rooms,       only: [:show, :create, :destroy]
    resources :messages,    only: [:create, :destroy]
    resources :vision_tags, only: [:show]
  end

  namespace :admin do
    get '/' => 'homes#top'

    resources :members, only: [:index, :show, :update] do
      member do
        get 'report'
      end
    end
    resources :searches, only: [:index, :show]
    resources :reports,  only: [:show, :update]
    resources :tags,     only: [:index, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,           presence: :true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :nickname,        presence: :true, length: { in: 1..15 }

  default_scope ->            { order(created_at: "DESC") }
  enum status:                { active: 0, banned: 1, inactive: 2 }
  enum reason_for_quit_genre: { no_chance_to_use: 0, hard_to_use: 1, others: 2 }

  has_many :posts,                 dependent: :destroy
  has_many :post_comments,         dependent: :destroy
  has_many :favorites,             dependent: :destroy
  has_many :messages,              dependent: :destroy
  has_many :entries,               dependent: :destroy
  has_many :rooms,                 through:   :entries

  has_many :reports,               class_name: "Report", foreign_key: "reporter_id", dependent: :destroy
  has_many :reverse_of_reports,    class_name: "Report", foreign_key: "reported_id", dependent: :destroy

  has_many :active_notifications,  class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  has_many :subscribes,            class_name: "Relationship", foreign_key: "subscriber_id", dependent: :destroy
  has_many :reverse_of_subscribes, class_name: "Relationship", foreign_key: "subscribed_id", dependent: :destroy
  has_many :subscribings,          through: :subscribes, source: :subscribed
  has_many :subscribers,           through: :reverse_of_subscribes, source: :subscriber

  has_one_attached :icon

  # <!---- ActiveStrage method ----!>
  def get_icon(width, height)
    unless icon.attached?
      file_path = Rails.root.join('app/assets/images/no-ion.jpg')
      icon.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
    icon.variant(resize_to_fill: [width, height]).processed
  end

  # <!---- Search method (for Admin) ----!>
  def self.search(keyword)
    where(["nickname LIKE? or email LIKE? or introduction LIKE?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

  # <!---- Relationship method ----!>
  def subscribe(member_id)
    subscribes.create(subscribed_id: member_id)
  end

  def unsubscribe(member_id)
    subscribes.find_by(subscribed_id: member_id).destroy
  end

  def subscribing?(member)
    subscribings.include?(member)
  end

  # <!---- Notification method ----!>
  # Relationship method
  def create_notification_subscribe!(current_member)
    mysub = Notification.where(["visiter_id = ? and visited_id = ? and action = ?", current_member.id, id, "subscribe"])
    if mysub.blank?
      notice = current_member.active_notifications.new(
        visited_id: id,
        action: "subscribe"
      )
      notice.save if notice.valid?
    end
  end

  # <!---- Guest Login method ----!>
  GUEST_MEMBER_EMAIL = "guest@example.com"
  def self.guest
    find_or_create_by!(email: GUEST_MEMBER_EMAIL) do |member|
      member.password = SecureRandom.urlsafe_base64
      member.nickname = "guestmember"
    end
  end

  def guest_member?
    email == GUEST_MEMBER_EMAIL
  end

  # <!---- Member's authentication (status) ----!>
  def active_for_authentication?
    super && (status == 'active')
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_member, except: [:index]

  def index
    @members = Member.all.page(params[:page]).per(8)
  end

  def show
    @report_count = Report.where(reported_id: @member.id).count
  end

  def update
    @member.update(member_params)
    redirect_to request.referer, notice: "ステータスを更新しました。"
  end

  private

  def member_params
    params.require(:member).permit(:status)
  end

  def set_member
    @member = Member.find(params[:id])
  end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/views/admin/members/_index.html.erb
<table class="table table-borderless">
  <thead>
    <tr>
      <th>登録日時</th>
      <th>ユーザーネーム</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr class="border-bottom">
        <td>
          <%= link_to admin_member_path(member) do %>
            <%= l member.created_at %>
          <% end %>
        </td>
        <td><%= member.nickname %></td>
        <td><%= member.status_i18n %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/members/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-2">
      <h4>会員一覧</h4>
        <%= render 'admin/members/index', members: @members %>
    </div>
  </div>
  <div class="row mb-5">
    <div class="mx-auto mb-5">
      <%= paginate @members, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/admin/members/show.html.erb
<div class="container">
  <h4 class="mt-3">
    "<%= link_to @member.nickname, member_path(@member) %>" (通報された回数：
    <%= link_to admin_search_path(@member.id) do %>
      <%= @report_count %>
    <% end %>回)
  </h4>
  <%= form_with model: @member, url: admin_member_path, method: :patch do |f| %>
    <div class="row mx-auto mt-5">
      <div class="col-md-2 offset-2 text-center">
        <%= image_tag @member.get_icon(130,130), class:"rounded-circle" %>
      </div>

      <div class="col-md-8 mt-5 d-flex">
        <p class="mt-5 pt-1">ステータス変更：</p>
        <%= f.select :status, Member.statuses_i18n.invert, {}, class:"form-control col-3 mt-5" %>
        <%= f.submit '変更する', class:"btn btn-danger px-3 ml-3 mt-5 rounded" %>
      </div>
    </div>

    <div class="row mt-3 mb-5">
      <div class="col-md-8 mx-auto">
        <div class="my-3">
          <h5>メールアドレス</h5>
          <p class="bg-light py-2 px-3 rounded-pill"><%= @member.email %></p>
        </div>

        <div class="my-5">
          <h5>ユーザーネーム</h5>
          <p class="bg-light py-2 px-3 rounded-pill">
            <%= @member.nickname %>
          </p>
        </div>

        <div class="my-5">
          <h5>自己紹介</h5>
          <% if @member.introduction.present? %>
            <p class="bg-light py-2 px-3 rounded-pill"><%= @member.introduction %></p>
          <% else %>
            <p class="my-3">自己紹介はありません</p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>