config/routes.rb
Rails.application.routes.draw do

  devise_for :members, controllers: {
    registrations: "public/registrations",
    sessions:      "public/sessions",
    passwords:     "public/passwords"
  }
  
  devise_scope :member do
    post "members/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get '/about'          => 'homes#about', as: 'about'

    resources :members, only: [:index, :show] do
      collection do
        get   'favorite'
        get   'deal'
        get   'quit_form'
        post  'confirm'
        patch 'quit'
      end
      resource :relationships, only: [:create, :destroy] do
        collection do
          get 'subscribings'
          get 'subscribers'
        end
      end
      resources :reports,  only: [:new, :create, :show] do
        collection do
          post 'confirm'
        end
      end
    end
    get   'members/information/edit' => 'members#edit'
    patch 'members/information'      => 'members#update'

    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource  :favorites,     only: [:create, :destroy]
      collection do
        get 'map'
      end
    end

    resources :notifications, only: [:destroy] do
      collection do
        delete 'destroy_all'
        patch  'notice'
      end
    end

    resources :searches,    only: [:index]
    resources :tags,        only: [:show]
    resources :rooms,       only: [:show, :create, :destroy]
    resources :messages,    only: [:create, :destroy]
    resources :vision_tags, only: [:show]
  end

  namespace :admin do
    get '/' => 'homes#top'

    resources :members, only: [:index, :show, :update] do
      member do
        get 'report'
      end
    end
    resources :searches, only: [:index, :show]
    resources :reports,  only: [:show, :update]
    resources :tags,     only: [:index, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :posts
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_tag, except: [:index, :create]

  def index
    @tags = Tag.all
    @tag  = Tag.new
  end

  def create
    tag = Tag.new(tag_params)
    tag.save
    redirect_to admin_tags_path, notice: "登録しました。"
  end

  def edit
  end

  def update
    @tag.update(tag_params)
    redirect_to admin_tags_path, notice: "更新しました。"
  end

  def destroy
    @tag.destroy
    redirect_to admin_tags_path, notice: "削除しました。"
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

  def set_tag
    @tag = Tag.find(params[:id])
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 my-5">
      <h4>ジャンル編集</h4>
      <%= form_with model: @tag, url: admin_tag_path(@tag), method: :patch do |f| %>
        <table class="table table-borderless">
          <thead>
            <tr>
              <th><%= f.text_field :name, class:"form-control" %></th>
              <th><%= f.submit '更新', class:"btn btn-outline-success form-control" %></th>
              <th>
                <%= link_to '削除', admin_tag_path(@tag), method: :delete,
                data: { confirm: "[重要]削除すると関連する投稿が全て削除されます。本当によろしいですか？" },
                class:"btn btn-outline-danger form-control" %>
              </th>
            </tr>
          </thead>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 offset-2 my-5">
      <h4>ジャンル投稿・一覧</h4>
      <%= form_with model: @tag, url: admin_tags_path, method: :post do |f| %>
        <table class="table mb-5">
          <thead class="table-borderless">
            <tr>
              <th></th>
              <th><%= f.text_field :name, placeholder: "ジャンル名", class:"form-control" %></th>
              <th><%= f.submit '登録', class:"btn btn-outline-info" %></th>
              <th></th>
            </tr>

            <% @tags.each do |tag| %>
              <tr>
                <th><%= l tag.updated_at %></th>
                <th><%= tag.name %></th>
                <th><%= link_to '編集', edit_admin_tag_path(tag), class:"btn btn-outline-success" %></th>
                <th>
                  <%= link_to '削除', admin_tag_path(tag), method: :delete,
                  data: { confirm: "[重要]削除すると関連する投稿が全て削除されます。本当によろしいですか？" },
                  class:"btn btn-outline-danger" %>
                </th>
              </tr>
            <% end %>
          </thead>
        </table>
      <% end %>
    </div>
  </div>
</div>