config/routes.rb
Rails.application.routes.draw do

  devise_for :members, controllers: {
    registrations: "public/registrations",
    sessions:      "public/sessions",
    passwords:     "public/passwords"
  }
  
  devise_scope :member do
    post "members/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get '/about'          => 'homes#about', as: 'about'

    resources :members, only: [:index, :show] do
      collection do
        get   'favorite'
        get   'deal'
        get   'quit_form'
        post  'confirm'
        patch 'quit'
      end
      resource :relationships, only: [:create, :destroy] do
        collection do
          get 'subscribings'
          get 'subscribers'
        end
      end
      resources :reports,  only: [:new, :create, :show] do
        collection do
          post 'confirm'
        end
      end
    end
    get   'members/information/edit' => 'members#edit'
    patch 'members/information'      => 'members#update'

    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource  :favorites,     only: [:create, :destroy]
      collection do
        get 'map'
      end
    end

    resources :notifications, only: [:destroy] do
      collection do
        delete 'destroy_all'
        patch  'notice'
      end
    end

    resources :searches,    only: [:index]
    resources :tags,        only: [:show]
    resources :rooms,       only: [:show, :create, :destroy]
    resources :messages,    only: [:create, :destroy]
    resources :vision_tags, only: [:show]
  end

  namespace :admin do
    get '/' => 'homes#top'

    resources :members, only: [:index, :show, :update] do
      member do
        get 'report'
      end
    end
    resources :searches, only: [:index, :show]
    resources :reports,  only: [:show, :update]
    resources :tags,     only: [:index, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :reporter, class_name: "Member"
  belongs_to :reported, class_name: "Member"

  validates :reason,  presence: :true

  enum is_supported: { waiting: 0, keep: 1, done: 2 }
  enum genre:        { inappropriate_content: 0, aggressive: 1, spam: 2, others: 3 }
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_report

  def show
  end

  def update
    @report.update(report_params)
    redirect_to request.referer, notice: "ステータスを更新しました。"
  end

  private

  def report_params
    params.require(:report).permit(:is_supported)
  end

  def set_report
    @report =  Report.find(params[:id])
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/_index.html.erb
<table class="table table-borderless">
  <thead>
    <tr>
      <th>通報日時</th>
      <th>通報者名</th>
      <th>ステータス</th>
      <th>通報ジャンル</th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr class="border-bottom">
        <td>
          <%= link_to admin_report_path(report) do %>
            <%= l report.created_at %>
          <% end %>
          </td>
        <td>
          <%= link_to admin_member_path(report.reporter_id) do %>
            <%= report.reporter.nickname %>
          <% end %>
        </td>
        <td><%= report.is_supported_i18n %></td>
        <td><%= report.genre_i18n %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/reports/show.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col-md-8 offset-2">
      <h4>通報詳細</h4>
      <%= form_with model: @report, url: admin_report_path, method: :patch do |f| %>
        <table class="table table-borderless">
          <thead>
            <tr>
              <th>通報者：</th>
              <th>
                <%= link_to admin_member_path(@report.reporter_id) do %>
                  <%= @report.reporter.nickname %>
                <% end %>
              </th>
            </tr>
          </thead>

          <thead>
            <tr>
              <th>ユーザーネーム：</th>
              <th>
                <%= link_to admin_member_path(@report.reported_id) do %>
                  <%= @report.reported.nickname %>
                <% end %>
              </th>
            </tr>
          </thead>

          <thead>
            <tr>
              <th>通報ジャンル：</th>
              <th><%= @report.genre_i18n %></th>
            </tr>
          </thead>

          <thead>
            <tr>
              <th>通報内容：</th>
              <th><%= @report.reason %></th>
            </tr>
          </thead>

          <thead>
            <tr>
              <th>ステータス変更：</th>
              <th class="d-flex">
                <%= f.select :is_supported, Report.is_supporteds_i18n.invert, {}, class:"form-control col-6" %>
                <%= f.submit '変更する', class:"btn btn-danger px-3 ml-3 rounded-pill" %>
              </th>
            </tr>
          </thead>
        </table>
      <% end %>
    </div>
  </div>
</div>