config/routes.rb
Rails.application.routes.draw do

  devise_for :members, controllers: {
    registrations: "public/registrations",
    sessions:      "public/sessions",
    passwords:     "public/passwords"
  }
  
  devise_scope :member do
    post "members/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get '/about'          => 'homes#about', as: 'about'

    resources :members, only: [:index, :show] do
      collection do
        get   'favorite'
        get   'deal'
        get   'quit_form'
        post  'confirm'
        patch 'quit'
      end
      resource :relationships, only: [:create, :destroy] do
        collection do
          get 'subscribings'
          get 'subscribers'
        end
      end
      resources :reports,  only: [:new, :create, :show] do
        collection do
          post 'confirm'
        end
      end
    end
    get   'members/information/edit' => 'members#edit'
    patch 'members/information'      => 'members#update'

    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource  :favorites,     only: [:create, :destroy]
      collection do
        get 'map'
      end
    end

    resources :notifications, only: [:destroy] do
      collection do
        delete 'destroy_all'
        patch  'notice'
      end
    end

    resources :searches,    only: [:index]
    resources :tags,        only: [:show]
    resources :rooms,       only: [:show, :create, :destroy]
    resources :messages,    only: [:create, :destroy]
    resources :vision_tags, only: [:show]
  end

  namespace :admin do
    get '/' => 'homes#top'

    resources :members, only: [:index, :show, :update] do
      member do
        get 'report'
      end
    end
    resources :searches, only: [:index, :show]
    resources :reports,  only: [:show, :update]
    resources :tags,     only: [:index, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div class="text-danger">
  <% model.errors.full_messages.each do |message| %>
    <b><%= message %></b><br>
  <% end %>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <p class="alert alert-<%= key %>">
    <div class="text-center py-3" data-aos="zoom-in" data-aos-duration="500">
      <%= value %>
    </div>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom py-3 text-center mt-5">
  <div class="container">
    <a class="text-light" href="https://github.com/yuna096740/Tabekiro_uo">
      Github link: created by Yuna096740
    </a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-xxl navbar-light mt-3">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%= render 'layouts/nav_modal_list', keyword: @keyword, tags: @tags %>

  <% if member_signed_in? %>
    <div data-aos="zoom-out-left" data-aos-duration="2000">
      <a data-toggle="collapse" href="#headerIcon" role="button" aria-expanded="false" aria-controls="#headerIcon">
        <span class="d-flex">
          <%= image_tag current_member.get_icon(60,60), class:"rounded-circle" %>
          <div class="notice-count-container">
            <% if @unchecked_notices.present? %>
              <div class="notice-count-box">
                <p class="notice-count"><%= @unchecked_notices.count %></p>
              </div>
            <% end %>
          </div>
        </span>
      </a>
    </div>
  <% end %>
</nav>

<div class="collapse navbar-collapse" id="navbarNav">
  <%= render 'layouts/nav_hamburger_list' %>
</div>
<% if member_signed_in? %>
  <%= render 'layouts/nav_icon', notices: @notices, unchecked_notices: @unchecked_notices %>
<% end %>

app/views/layouts/_nav_hamburger_list.html.erb
<ul class="navbar-nav mx-5">
  <li class="nav-item">
    <%= link_to root_path, class:"nav-link" do %>
      <%= image_tag 'topTopLOGO.svg' %>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to about_path, class:"nav-link" do %>
      <%= image_tag 'topAboutLOGO.svg' %>
    <% end %>
  </li>

  <% unless member_signed_in? || admin_signed_in? %>
    <li class="nav-item">
      <%= link_to new_member_session_path, class:"nav-link" do %>
        <%= image_tag 'loginLOGO.svg' %>
      <% end %>
    </li>

    <li class="nav-item">
      <%= link_to new_member_registration_path, class:"nav-link" do %>
        <%= image_tag 'newsessionsLOGO.svg' %>
      <% end %>
    </li>
  <% end %>

  <% if admin_signed_in? %>
    <li class="nav-item">
      <%= link_to admin_path, class:"nav-link" do %>
        <%= image_tag 'topReportIndexLOGO.svg' %>
      <% end %>
    </li>

    <li class="nav-item">
      <%= link_to admin_members_path, class:"nav-link" do %>
        <%= image_tag 'topMemberIndexLOGO.svg' %>
      <% end %>
    </li>

    <li class="nav-item">
      <%= link_to admin_tags_path, class:"nav-link" do %>
        <%= image_tag 'topCreateTagLOGO.svg' %>
      <% end %>
    </li>

    <li class="nav-item">
      <%= link_to destroy_admin_session_path, method: :delete, class:"nav-link" do %>
        <%= image_tag 'topAdminLogOutLOGO.svg' %>
      <% end %>
    </li>
  <% elsif not admin_signed_in? || member_signed_in? %>
    <li class="nav-item">
      <%= link_to new_admin_session_path, class:"nav-link" do %>
        <%= image_tag 'topAdminLoginLOGO.svg' %>
      <% end %>
    </li>

    <li class="nav-item">
      <%= link_to members_guest_sign_in_path, method: :post, class:"nav-link" do %>
        <%= image_tag 'guestLoginLOGO.svg' %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/layouts/_nav_icon.html.erb
<div class="nav-collapse collapse offset-md-10" id="headerIcon">

  <%= render 'layouts/notice_modal', unchecked_notices: unchecked_notices, notices: notices %>

  <%= link_to members_path do %>
    <h5 class="dropdown-item py-2 pr-5">
      <i class="fas fa-user-circle"></i>
      <%= image_tag 'topMyPageLOGO.svg', class:"mb-1" %>
    </h5>
  <% end %>

  <%= link_to deal_members_path do %>
    <h5 class="dropdown-item py-2 pr-5">
      <i class="fas fa-fish"></i>
      <%= image_tag 'topMyDealLOGO.svg' %>
    </h5>
  <% end %>

  <%= link_to favorite_members_path do %>
    <h5 class="dropdown-item py-2 pr-5">
      <i class="fas fa-heart"></i>
      <%= image_tag 'topMyFavoLOGO.svg', class:"mb-1" %>
    </h5>
  <% end %>

  <%= link_to subscribers_member_relationships_path(current_member) do %>
    <h5 class="dropdown-item py-2 pr-5">
      <i class="fas fa-user-plus"></i>
      <%= image_tag 'topMySubscriberLOGO.svg', class:"mb-1" %>
    </h5>
  <% end %>

  <%= link_to subscribings_member_relationships_path(current_member) do %>
    <h5 class="dropdown-item py-2 pr-5">
      <i class="fas fa-user-tie mr-2"></i>
      <%= image_tag 'topMySubscribedLOGO.svg' %>
    </h5>
  <% end %>

  <%= link_to destroy_member_session_path, method: :delete do %>
    <h5 class="dropdown-item py-2 pr-5">
      <i class="fas fa-sign-out-alt"></i>
      <%= image_tag 'topSignOutLOGO.svg', class:"mb-1" %>
    </h5>
  <% end %>
</div>

app/views/layouts/_nav_modal_list.html.erb
<div data-toggle="modal" data-target="#exampleModal">
  <%= image_tag 'Tabekiro-uo-mini-logo.svg', style:"width:160px;" %>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= image_tag 'navModal.svg', class:"file-fluid" %></h5>
        <button type="button" class="btn-close btn btn-outline-secondary" data-dismiss="modal" aria-label="Close">
          <i class="fas fa-times"></i>
        </button>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <%= link_to posts_path do %>
            <%= image_tag 'topIndexLOGO.svg', class:"m-2", style:"width:80%;" %>
          <% end %>

          <% if member_signed_in? %>
            <%= link_to new_post_path do %>
              <%= image_tag 'topNewLOGO.svg', class:"m-2" %>
            <% end %>
          <% end %>

          <%= link_to map_posts_path do %>
            <%= image_tag 'mapsearchLOGO.svg', class:"m-2" %>
          <% end %>
        </div>
      </div>

      <div class="modal-body">
        <div class="container-fluid">
          <a data-toggle="collapse" href="#headerTag" aria-expanded="false" aria-controls="#headerTag">
            <%= image_tag 'topGenreLOGO.svg', class:"ml-2" %>
          </a>
        </div>
      </div>

      <div class="modal-body">
        <div class="container-fluid">
          <div class="collapse" id="headerTag">
            <div class="d-flex">
              <% tags.each do |tag| %>
                <hr>
                <h5><%= link_to tag.name, tag_path(tag), class:"text-dark mr-3" %></h5>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <%= render 'public/searches/form', keyword: keyword %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notice_modal.html.erb
<div data-toggle="modal" data-target="#noticeModal">
  <% if unchecked_notices.present? %>
    <h5 class="dropdown-item py-2">
      <%= link_to notice_notifications_path, method: :patch, remote: true do %>
        <span class="text-danger" id="noticeRedLOGO">
          <i class="fas fa-bell text-danger mr-2"></i>
            <%= image_tag 'topNoticeRedLOGO.svg', class:"mb-1" %>
        </span>
      <% end %>
    </h5>
  <% else %>
    <h5 class="dropdown-item py-2">
      <%= render 'public/notifications/notice_logo' %>
    </h5>
  <% end %>
</div>

<div class="modal fade" id="noticeModal" tabindex="-1" role="dialog" aria-labelledby="noticeLabel" ariahidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-title ml-3" id="noticeLabel">
          <%= image_tag 'topNoticeLOGO.svg' %>
        </div>

        <% if notices.exists? %>
          <%= link_to destroy_all_notifications_path, method: :delete, class:"text-dark" do %>
            <p class="mx-1">ALL<i class="fas fa-trash"></i></p>
          <% end %>
        <% end %>
      </div>

      <div class="modal-body" id="notice">
        <% notices = notices.where.not(visiter_id: current_member.id) %>

        <% if notices.exists? %>
          <%= render 'layouts/notice_modal_contents', unchecked_notices: unchecked_notices, notices: notices %>
        <% else %>
          <p id="nonNotice">通知はありません</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notice_modal_contents.html.erb
<% notices.each do |notice| %>
  <% visiter = notice.visiter %>
  <% visited = notice.visited %>
  <div class="d-flex">
    <%= link_to member_path(visiter) do %>
      <%= image_tag visiter.icon, size: "20x20", class:"rounded-circle" %>
    <% end %>

    <%= visiter.nickname %>さんが
    <% if notice.action == 'subscribe' %>
      <%= render 'public/notifications/subscribe_notice', notice: notice %>
    <% elsif notice.action == 'favorite' %>
      <%= render 'public/notifications/fav_notice', notice: notice %>
    <% elsif notice.action == 'comment' %>
      <%= render 'public/notifications/comment_notice', notice: notice, visited: visited %>
    <% else %>
      <%= render 'public/notifications/dm_notice', notice: notice, visited: visited %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>たべきろ魚</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag('favicon.ico') %>
    <script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.js"></script>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script src="https://kit.fontawesome.com/0e15a7e9ae.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
  <script>
    AOS.init();
    bsCustomFileInput.init();
  </script>
</html>